services:
  - type: web
    name: image-classifier-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 